[workspace]
members = [
    "01/hello_world",
    "02/chapter2",
    "03/chapter3",
    "04/chapter4",
    "05/chapter5",
    "07/chapter7",
    "08/chapter8",
    "09/chapter9",
    "10/chapter10"
]
