[package]
name = "chapter15"
version = "0.1.0"
authors = ["Thibault Gagnaux <thibault.gagnaux@bit.admin.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
